import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CardGrid from '../components/CardGrid';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Vacationlands 1946</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto mt-5">
        <h1 className="font-decor text-7xl text-purple text-center">
          Vacationlands
        </h1>
        <h2 className="mt-2 font-sans text-7xl text-black text-center">1946</h2>

        <h3 className="font-sans text-4xl text-black text-center mt-9 mb-3">
          Select a destination to begin
        </h3>

        <CardGrid gridCols="3" border="purple" highlight="yellow" />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/boringem/vacationlands"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn More
        </a>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
